<!DOCTYPE html>
<html>
<head>
    <title>Laporan Peminjaman Ruangan </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 30px;
            color: #333;
        }
        h1 {
            text-align: center;
            font-size: 28px;
            margin-bottom: 20px;
            color: #2c3e50;
            text-transform: uppercase;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            text-align: left;
            padding: 10px;
            border: 1px solid #ddd;
        }
        table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .section-title {
            font-weight: bold;
            font-size: 20px;
            margin-bottom: 15px;
            color: #495057;
            border-bottom: 2px solid #ddd;
            padding-bottom: 5px;
        }
        .image-container {
            text-align: center;
            margin-top: 15px;
        }
        .image-container img {
            max-width: 300px; /* Ukuran gambar lebih kecil */
            height: auto;
            border: 1px solid #ddd;
            padding: 5px;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .no-image {
            text-align: center;
            font-style: italic;
            color: #888;
        }
        .divider {
            margin: 25px 0;
            border-top: 2px solid #ddd;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #777;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <h1>Laporan Peminjaman Ruangan</h1>

    <table>
        <tr>
            <th>ID Laporan</th>
            <td>{{ $pelaporan->id_lapor_ruangan }}</td>
        </tr>
        <tr>
            <th>Tanggal Laporan</th>
            <td>{{ \Carbon\Carbon::parse($pelaporan->datetime)->format('d F Y') }}</td>
        </tr>
        <tr>
            <th>Dibuat Oleh</th>
            <td>{{ $pelaporan->mahasiswa->nama_mahasiswa ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Deskripsi</th>
            <td>{{ $pelaporan->deskripsi }}</td>
        </tr>
    </table>

    <div class="divider"></div>

    <div class="section">
        <p class="section-title">Foto Kondisi Awal</p>
        <div class="image-container">
            @if($pelaporan->foto_awal)
                <img src="{{ public_path('storage/' . $pelaporan->foto_awal) }}" alt="Foto Kondisi Awal">
            @else
                <p class="no-image">Tidak ada foto.</p>
            @endif
        </div>
    </div>

    <div class="divider"></div>

    <div class="section">
        <p class="section-title">Foto Kondisi Akhir</p>
        <div class="image-container">
            @if($pelaporan->foto_akhir)
                <img src="{{ public_path('storage/' . $pelaporan->foto_akhir) }}" alt="Foto Kondisi Akhir">
            @else
                <p class="no-image">Tidak ada foto.</p>
            @endif
        </div>
    </div>

    <div class="footer">
        <p>Generated by Sistem Peminjaman Fakultas Rekayasa Industri</p>
    </div>
</body>
</html>

